server:
    port: 8080
    context-path:

logging:
    level:
        tk.mybatis: TRACE

druid:
    driver-class: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.66.101:3306/work_flow?useUnicode=true&characterEncoding=utf-8
    username: root
    password: quspacedragon@123!&*
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.quspacedragon.workflow.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
umen:
    appkey: 59dcde4cb27b0a77c1001057
    message-secret: 7f019eabf5ba703acaf050f3f1759dba
    app-master-secret: h1jqsjymlllrlvsiorkneeweqtg6q62a
