server:
    port: 8080
    context-path:

logging:
    level:
        tk.mybatis: TRACE
        org.springframework.web: DEBUG
        com.github.binarywang.demo.wx.miniapp: DEBUG

druid:
    driver-class: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.132.66.101:3306/work_flow
    username: root
    password: quspacedragon@123!&*
    initial-size: 1
    min-idle: 1
    max-active: 20
    test-on-borrow: true

spring:
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request


mybatis:
    type-aliases-package: tk.mybatis.springboot.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.quspacedragon.workflow.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

debug: true
wechat:
  miniapp:
    appid: 111
    secret: 111
    token: 111
    aesKey: 111
    msgDataFormat: JSON